[package]
name = "chirp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gumdrop = "0.8.1"
hex-wrapper = "1.3.2"
minifb = "0.24.0"
owo-colors = "^3"
rand = "0.8.5"
rhexdump = "0.1.1"
serde = { version = "^1.0", features = ["derive"] }
thiserror = "1.0.39"
